### ISSUE TITLE
further explaination needs  reader_sleep_time=12

### ISSUE THREAD

**Issue by ahmadjd94** [NerdWalletOSS/kinesis-python#18]
I have a question regarding setting the sleep interval for the subprocesses in the consumer 
`reader_sleep_time=12`
should setting the variable actually slow down the loop (the __iter__ overrided in the class), or does it internally set the sleep interval for the subprocess that is listening the stream?

I could not find anything regarding that in the documentation.
thanks

**Comment by borgstrom** [comment]
Hi @ahmadjd94,

Pardon the delay on replying to this issue.

The `reader_sleep_time` controls how often the subprocess that reads from each shard polls the Kinesis end point.  The default value of `1.0` is generally sufficient if you're the only thing reading from the shards.  You would want to supply a larger value if there are multiple different systems reading from the same shards to prevent having to deal with throttling from the AWS APIs.
