### ISSUE TITLE
ModuleNotFoundError in Python3

### ISSUE THREAD

**Issue by max-lg** [NerdWalletOSS/kinesis-python#6]
Thanks for this library! It doesn't work out of the box with python3 because "Queue" was renamed to "queue". 
I have a branch of this project that handles this at: https://github.com/max-lg/kinesis-python/tree/python3compatability
I'm not sure if it meets your coding standards or if you intend to support python3 but I'd be happy to send a pull request or feel free to copy/paste the code snippet :)

**Comment by borgstrom** [comment]
This was fixed in #8
